version: 2

before:
  hooks:
    - make clean
    - go generate ./...
    - go mod tidy
    - ./scripts/generate-changelog.sh {{ .Tag }}
    - ./scripts/generate-release-notes.sh {{ .Tag }}

builds:
  - main: ./cmd/emojify
    binary: emojify
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/damienbutt/emojify-go/internal/version.Version={{.Version}}
      - -X github.com/damienbutt/emojify-go/internal/version.Commit={{.Commit}}
      - -X github.com/damienbutt/emojify-go/internal/version.Date={{.Date}}
      - -X github.com/damienbutt/emojify-go/internal/version.BuiltBy=goreleaser

archives:
  - files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - man/*.1
    format_overrides:
      - goos: windows
        formats: [zip]

source:
  enabled: true

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

nfpms:
  - maintainer: Damien Butt <22627489+damienbutt@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/emojify/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/emojify/README.md

release:
  github:
    owner: damienbutt
    name: emojify-go
  draft: false
  mode: replace
  footer: |
    **Full Changelog**: https://github.com/damienbutt/emojify-go/compare/{{ .PreviousTag }}...{{ .Tag }}

homebrew_casks:
  - repository:
      owner: damienbutt
      name: homebrew-tap
      token: "{{ .Env.RELEASE_TOKEN }}"
    name: emojify-go
    binary: emojify
    homepage: https://github.com/damienbutt/emojify-go
    description: Lighting fast Emoji conversion on the command line 😱
    manpages:
      - man/emojify.1

scoops:
  - name: emojify-go
    repository:
      owner: damienbutt
      name: scoop-bucket
      token: "{{ .Env.RELEASE_TOKEN }}"
    homepage: https://github.com/damienbutt/emojify-go
    description: Lighting fast Emoji conversion on the command line 😱
    license: MIT

winget:
  - publisher: damienbutt
    release_notes_url: "https://github.com/damienbutt/emojify-go/releases/tag/{{.Tag}}"
    license_url: https://github.com/damienbutt/emojify-go/blob/main/LICENSE
    short_description: "Lighting fast Emoji conversion on the command line 😱"
    license: MIT
    repository:
      owner: "damienbutt"
      name: winget-pkgs
      token: "{{ .Env.RELEASE_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        # check_boxes: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

aurs:
  - name: emojify-go-bin
    homepage: https://github.com/damienbutt/emojify-go
    description: Lighting fast Emoji conversion on the command line 😱
    maintainers:
      - Damien Butt <22627489+damienbutt@users.noreply.github.com>
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/emojify-go-bin.git
    provides:
      - emojify
    conflicts:
      - emojify
    package: |-
      # bin
      install -Dm755 "./emojify" "${pkgdir}/usr/bin/emojify"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/emojify-go/LICENSE"

      # documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/emojify-go/README.md"
      install -Dm644 man/emojify.1 "${pkgdir}/usr/share/man/man1/emojify.1"
    skip_upload: false

aur_sources:
  - name: emojify-go
    homepage: https://github.com/damienbutt/emojify-go
    description: Lighting fast Emoji conversion on the command line 😱
    maintainers:
      - Damien Butt <22627489+damienbutt@users.noreply.github.com>
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/emojify-go.git
    provides:
      - emojify
    conflicts:
      - emojify
    makedepends:
      - go
      - git
    prepare: |-
      cd "$srcdir/{{ .ProjectName }}-{{ .Version }}"

      # Set up Go environment for reproducible builds
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      export CGO_ENABLED=0

      # Download dependencies
      go mod download
    build: |-
      cd "$srcdir/{{ .ProjectName }}-{{ .Version }}"

      # Build the binary with proper flags
      export CGO_ENABLED=0
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      export LDFLAGS="-linkmode=external -extldflags \"${LDFLAGS}\""

      go build \
        -ldflags="-s -w -X github.com/damienbutt/emojify-go/internal/version.Version={{ .Version }} -X github.com/damienbutt/emojify-go/internal/version.Commit={{ .Commit }} -X github.com/damienbutt/emojify-go/internal/version.Date={{ .Date }} -X github.com/damienbutt/emojify-go/internal/version.BuiltBy=makepkg ${LDFLAGS}" \
        -o emojify \
        ./cmd/emojify
    package: |-
      cd "$srcdir/{{ .ProjectName }}-{{ .Version }}"

      # Install binary
      install -Dm755 emojify "${pkgdir}/usr/bin/emojify"

      # Install license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

      # Install documentation
      install -Dm644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"
      install -Dm644 man/emojify.1 "${pkgdir}/usr/share/man/man1/emojify.1"
    skip_upload: false

dockers:
  - image_templates:
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-amd64"
      - "ghcr.io/damienbutt/emojify:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-arm64"
      - "ghcr.io/damienbutt/emojify:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/damienbutt/emojify:{{ .Version }}"
    image_templates:
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-amd64"
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-arm64"
  - name_template: "ghcr.io/damienbutt/emojify:latest"
    image_templates:
      - "ghcr.io/damienbutt/emojify:latest-amd64"
      - "ghcr.io/damienbutt/emojify:latest-arm64"
