# GoReleaser configuration for emojify-go
version: 2

project_name: emojify-go

# Output directory for artifacts
dist: dist

before:
  hooks:
    - go mod tidy
    - go generate ./...
    # Generate full CHANGELOG.md for the repository
    - go tool git-chglog --next-tag {{ .Tag }} --output CHANGELOG.md
    # Generate release-specific changelog for GitHub release
    - go tool git-chglog --next-tag {{ .Tag }} {{ .Tag }} --output RELEASE_NOTES.md

builds:
  - id: emojify
    main: ./cmd/emojify
    binary: emojify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/damienbutt/emojify-go/internal/version.Version={{.Version}}
      - -X github.com/damienbutt/emojify-go/internal/version.Commit={{.Commit}}
      - -X github.com/damienbutt/emojify-go/internal/version.Date={{.Date}}
      - -X github.com/damienbutt/emojify-go/internal/version.BuiltBy=goreleaser

archives:
  - id: "default"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - completions/**/*
      - docs/man/*.1

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  # Disable GoReleaser's built-in changelog generation
  # Use git-chglog generated CHANGELOG.md instead
  disable: true

# Git configuration for tagging and changelog commits
git:
  tag_sort: -version:refname
  ignore_tags:
    - "nightly"

# Homebrew formula (stored in main repo)
homebrew_casks:
  - repository:
      owner: damienbutt
      name: homebrew-tap
    name: emojify-go
    homepage: "https://github.com/damienbutt/emojify-go"
    description: "🎭 Transform plain text into expressive emoji-rich content"
    license: "MIT"
    directory: Casks
    binary: emojify
    manpages:
      - docs/man/emojify.1
    completions:
      bash: completions/emojify.bash
      zsh: completions/emojify.zsh
      fish: completions/emojify.fish

# Scoop bucket for Windows - targeting main repository
scoops:
  - name: emojify-go
    repository:
      owner: ScoopInstaller
      name: Main
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
    url_template: "https://github.com/damienbutt/emojify-go/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/damienbutt/emojify-go"
    description: "Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

# Chocolatey package for Windows
chocolateys:
  - name: emojify-go
    title: Emojify-Go
    authors: Damien Butt
    project_url: https://github.com/damienbutt/emojify-go
    url_template: "https://github.com/damienbutt/emojify-go/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: "https://raw.githubusercontent.com/damienbutt/emojify-go/main/img/emojify-icon.png"
    copyright: 2025 Damien Butt
    license_url: https://github.com/damienbutt/emojify-go/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/damienbutt/emojify-go
    docs_url: https://github.com/damienbutt/emojify-go/blob/main/README.md
    bug_tracker_url: https://github.com/damienbutt/emojify-go/issues
    tags: "emoji cli command-line text-processing golang"
    summary: Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis
    description: |
      {{ .ProjectName }} is a lightning-fast Go rewrite of the original emojify bash script.
      It replaces emoji aliases (like :grin:) with actual emoji characters with 169.9x
      better performance. Perfect for processing git logs, documentation, and any text
      containing emoji aliases.
    release_notes: "https://github.com/damienbutt/emojify-go/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"

# WinGet package for Windows
winget:
  - name: emojify-go
    publisher: damienbutt
    license: MIT
    homepage: https://github.com/damienbutt/emojify-go
    short_description: Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis
    description: |
      Emojify-Go is a lightning-fast Go rewrite of the original emojify bash script.
      It replaces emoji aliases (like :grin:) with actual emoji characters with 169.9x
      better performance. Perfect for processing git logs, documentation, and any text
      containing emoji aliases.
    repository:
      owner: damienbutt
      name: winget-pkgs
      branch: emojify-go-{{.Version}}
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

# Linux packages
nfpms:
  - id: packages
    package_name: emojify-go
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Damien Butt
    homepage: https://github.com/damienbutt/emojify-go
    maintainer: Damien Butt <damien@example.com>
    description: |-
      Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis.
      Emojify-Go is a lightning-fast Go rewrite of the original emojify bash script
      with 169.9x better performance.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    recommends:
      - less
    suggests:
      - zsh
      - bash
    bindir: /usr/bin
    section: utils
    priority: optional
    meta: true
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/emojify/LICENSE
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/emojify/README.md
        file_info:
          mode: 0644
    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
    rpm:
      group: Applications/Text
      compression: lzma
      # GPG signing is optional and can be added later
      # signature:
      #   key_file: "{{ .Env.GPG_KEY_FILE }}"
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

# Snapcraft
snapcrafts:
  - name: emojify-go
    publish: true
    summary: Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis
    description: |
      Emojify-Go is a lightning-fast Go rewrite of the original emojify bash script
      with 169.9x better performance. It replaces emoji aliases (like :grin:) with
      actual emoji characters. Perfect for processing git logs, documentation, and
      any text containing emoji aliases.

      Features:
      - 169.9x faster than original bash version
      - Support for 2500+ emojis
      - Pipeline-friendly
      - Cross-platform compatibility
      - Zero dependencies
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    channel_templates:
      - edge
      - beta
      - candidate
      - stable
    apps:
      emojify:
        command: emojify
        plugs: ["home", "removable-media"]

# AUR packages
aurs:
  # Binary package (pre-built binary) - GoReleaser only supports binary packages
  - name: emojify-go-bin
    homepage: https://github.com/damienbutt/emojify-go
    description: Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis (binary)
    maintainers:
      - "Damien Butt <damien at example dot com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/emojify-go-bin.git"
    depends:
      - glibc
    package: |-
      # bin
      install -Dm755 "./emojify" "${pkgdir}/usr/bin/emojify"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/emojify-go/LICENSE"

      # documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/emojify-go/README.md"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    skip_upload: false

# Note: emojify-go (source package) must be created manually on AUR
# GoReleaser only supports binary AUR packages

# Nix packages
nix:
  - name: emojify-go
    repository:
      owner: damienbutt
      name: nur-packages
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/damienbutt/emojify-go"
    description: "Lightning-fast Go rewrite of emojify - convert emoji aliases to Unicode emojis"
    license: "mit"
    path: pkgs/emojify-go/default.nix
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    skip_upload: false

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-amd64"
      - "ghcr.io/damienbutt/emojify:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - go.mod
      - go.sum
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-arm64"
      - "ghcr.io/damienbutt/emojify:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - go.mod
      - go.sum
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/damienbutt/emojify:{{ .Version }}"
    image_templates:
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-amd64"
      - "ghcr.io/damienbutt/emojify:{{ .Version }}-arm64"
  - name_template: "ghcr.io/damienbutt/emojify:latest"
    image_templates:
      - "ghcr.io/damienbutt/emojify:latest-amd64"
      - "ghcr.io/damienbutt/emojify:latest-arm64"

release:
  github:
    owner: damienbutt
    name: emojify
  draft: false
  prerelease: auto
  mode: replace
  # The body will be populated from RELEASE_NOTES.md via CLI flag or CI
  header: |
    ## Installation

    ### macOS (Homebrew)
    ```bash
    brew install damienbutt/emojify-go/emojify-go
    ```

    ### Windows (Scoop)
    ```powershell
    scoop bucket add main
    scoop install emojify-go
    ```

    ### Windows (Chocolatey)
    ```powershell
    choco install emojify-go
    ```

    ### Windows (WinGet)
    ```powershell
    winget install damienbutt.emojify-go
    ```

    ### Linux (DEB/RPM)
    Download the appropriate package from the release assets.

    ### Arch Linux (AUR)
    ```bash
    yay -S emojify-go-bin
    ```

    ### Docker
    ```bash
    docker run --rm ghcr.io/damienbutt/emojify:latest "Hello :wave: World"
    ```
  footer: |
    **Full Changelog**: https://github.com/damienbutt/emojify-go/compare/{{ .PreviousTag }}...{{ .Tag }}
