services:
  emojify-go:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    image: ghcr.io/damienbutt/emojify-go:latest
    container_name: emojify-go
    restart: never
